version: '3.4'

services:
  sb-fakeapi:
      image: ${DOCKER_REGISTRY}sb-fakeapi
      container_name: sb-fakeapi
      hostname: sb-fakeapi
      restart: unless-stopped
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: SpeedBracketsFakeAPI\Dockerfile
      environment:
        ASPNETCORE_ENVIRONMENT: Production
        ASPNETCORE_URLS: http://+:5050

networks:
  default:
    external:
      name: nat
